### PR TITLE
Thunderhub 0.13.31

### PR DESCRIPTION
**Pull request by remcoros**
Using the current version on the marketplace has a serious bug with the boltz service. You can't claim your swaps and you end up with stuck htlcs.

About replacing the thunderhub.patch with a new Dockerfile:

I removed the .patch file and copied the newer Dockerfile of thunderhub and did the modifications manually. The patch file was not applied by the Makefile or automated in any way, so that got me confused at first and also doesn't work with the github actions. No other service that I know does this and it can be error prone if automated and upstream makes incompatible changes. 
Using our own Dockerfile and diffing manually when updating the git submodule is pretty easy to maintain imo. 

supersedes #26 I already started working on this when I saw that PR and this was just quicker to push :)

### CODE REVIEW

**Comment by remcoros** [comment]
I asked boltz exchange support what the status was of the unreleased thunderhub changes upstream. That got things rolling and there's now a 0.13.31 release of thunderhub with the notable change of support for taproot swaps (cheaper fees for claim transactions).

updated this PR to use the latest release.

**Comment by kilrau** [comment]
We are excited to get this one merged, any feedback yet?

**Review by k0gen — APPROVED** [review]
Approved 🤌

**Comment by kilrau** [comment]
Thank you!

**Pull request merged**
